language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build
deploy:
  provider: surge
  skip_cleanup: true
  domain: UdiBen.surge.sh
  project: ./build/
on:
  branch: master
env:
  SURGE_TOKEN: d07641d4d8d0dfccb4eee665379dadcc
  SURGE_LOGIN: sabaudi@gmail.com
